In [1]:
import pandas as pd
import numpy as np

In [2]:
pip install SQLAlchemy

Collecting SQLAlchemy
  Downloading sqlalchemy-2.0.48-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from SQLAlchemy)
  Downloading greenlet-3.3.2-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from SQLAlchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.48-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ----------------------------- ---------- 1.6/2.1 MB 12.5 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 9.4 MB/s  0:00:00
Downloading greenlet-3.3.2-cp314-cp314-win_amd64.whl (232 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, greenlet, SQLAlchemy

   ---------------------------------------- 0/3 [typing-extensions]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   ---------------------------------------- 3/3 [SQLAlchemy]

Successfully installed SQLAlchemy-2.0.48 greenlet-3.3.2 typing-extensions-4.15.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
from sqlalchemy import create_engine,text

In [7]:
pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

In [17]:
username = r'SERHANOZTASASUS\serha'
password = ''
database = 'Data_Science'
servername = r'SerhanOZTASASUS\SQLEXPRESS'
# this is for sql authentication: "mssql+pyodbc://{username}:{password}@{servername}/{database}"
#    "?driver=ODBC+Driver+17+for+SQL+Server"
engine = create_engine(f"mssql+pyodbc://{servername}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes")
print(engine)

Engine(mssql+pyodbc://SerhanOZTASASUS\SQLEXPRESS/Data_Science?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes)

In [21]:
with engine.connect() as conn:
    # for table in ['sales', 'item_categories']:
    df = pd.read_sql(text(f'select * from sales'), conn)
    # print(f'table : sales')
    # print(df.to_string())
df.reset_index()

,index,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit,profit_margin_pct,shipping_days,order_year,order_month,order_quarter
0,0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,651.210022,524.960022,2.920026e+06,2.353921e+06,5.661050e+05,19.389999,16,2011,1,1
1,1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,47.450001,31.790001,5.100875e+04,3.417425e+04,1.683450e+04,33.000000,26,2015,12,4
2,2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,2011-01-13,141515767,2011-02-01,6515,154.059998,90.930000,1.003701e+06,5.924089e+05,4.112919e+05,40.980000,19,2011,1,1
3,3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.270020,502.540009,5.134318e+06,3.861015e+06,1.273304e+06,24.799999,25,2012,9,3
4,4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.450001,31.790001,1.656480e+05,1.109789e+05,5.466906e+04,33.000000,39,2015,10,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,Asia,Laos,Beverages,Online,H,2014-07-15,199342048,2014-07-31,8597,47.450001,31.790001,4.079277e+05,2.732986e+05,1.346290e+05,33.000000,16,2014,7,3
9996,9996,Europe,Liechtenstein,Cosmetics,Online,C,2012-10-27,763044106,2012-11-01,562,437.200012,263.329987,2.457064e+05,1.479915e+05,9.771494e+04,39.770000,5,2012,10,4
9997,9997,Sub-Saharan Africa,Democratic Republic of the Congo,Vegetables,Offline,M,2013-02-14,848579967,2013-03-20,2524,154.059998,90.930000,3.888474e+05,2.295073e+05,1.593401e+05,40.980000,34,2013,2,1
9998,9998,Sub-Saharan Africa,South Africa,Meat,Online,L,2017-02-19,298185956,2017-02-22,8706,421.890015,364.690002,3.672974e+06,3.174991e+06,4.979832e+05,13.560000,3,2017,2,1
9999,9999,Asia,Mongolia,Snacks,Offline,M,2016-04-12,824410903,2016-04-16,361,152.580002,97.440002,5.508138e+04,3.517584e+04,1.990554e+04,36.139999,4,2016,4,2

In [23]:
with engine.connect( ) as conn:
    df_2 = pd.read_sql(text("""
    SELECT
 TRY_CAST([region] AS NVARCHAR(MAX)) AS [region]
,TRY_CAST([country] AS NVARCHAR(MAX)) AS [country]
,TRY_CAST([item_type] AS NVARCHAR(MAX)) AS [item_type]
,TRY_CAST([sales_channel] AS NVARCHAR(MAX)) AS [sales_channel]

,SUM(TRY_CAST(COALESCE([units_sold],0)		as FLOAT))	AS [units_sold]
,SUM(TRY_CAST(COALESCE([unit_price],0)		as FLOAT))	AS [unit_price]
,SUM(TRY_CAST(COALESCE([unit_cost],0)		as FLOAT))	AS [unit_cost]
,SUM(TRY_CAST(COALESCE([total_revenue],0)	as FLOAT))	AS [total_revenue]
,SUM(TRY_CAST(COALESCE([total_cost],0)		as FLOAT))	AS [total_cost]
,SUM(TRY_CAST(COALESCE([total_profit],0)	as FLOAT))	AS [total_profit]


FROM [dbo].[sales]

GROUP BY
 TRY_CAST([region] AS NVARCHAR(MAX))
,TRY_CAST([country] AS NVARCHAR(MAX)) 
,TRY_CAST([item_type] AS NVARCHAR(MAX)) 
,TRY_CAST([sales_channel] AS NVARCHAR(MAX))
;
"""), conn)
df_2

,region,country,item_type,sales_channel,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit
0,Asia,Bangladesh,Baby Food,Online,6432.0,510.559998,318.839996,1.641961e+06,1.025389e+06,6.165715e+05
1,Asia,Bangladesh,Beverages,Offline,3959.0,94.900002,63.580002,1.878545e+05,1.258566e+05,6.199794e+04
2,Asia,Bangladesh,Cereal,Offline,38394.0,1028.499985,585.550003,7.897646e+06,4.496321e+06,3.401324e+06
3,Asia,Bangladesh,Cereal,Online,29433.0,822.799988,468.440002,6.054368e+06,3.446899e+06,2.607470e+06
4,Asia,Bangladesh,Clothes,Offline,5223.0,109.279999,35.840000,5.707694e+05,1.871923e+05,3.835771e+05
...,...,...,...,...,...,...,...,...,...,...
4002,Sub-Saharan Africa,Zimbabwe,Personal Care,Online,18478.0,163.460007,113.339996,1.510207e+06,1.047148e+06,4.630587e+05
4003,Sub-Saharan Africa,Zimbabwe,Snacks,Offline,2333.0,152.580002,97.440002,3.559691e+05,2.273275e+05,1.286416e+05
4004,Sub-Saharan Africa,Zimbabwe,Snacks,Online,13981.0,305.160004,194.880005,2.133221e+06,1.362309e+06,7.709124e+05
4005,Sub-Saharan Africa,Zimbabwe,Vegetables,Offline,11441.0,308.119995,181.860001,1.762600e+06,1.040330e+06,7.222703e+05
4006,Sub-Saharan Africa,Zimbabwe,Vegetables,Online,22504.0,462.179993,272.790001,3.466966e+06,2.046289e+06,1.420678e+06