In [3]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine,text

username = r'AzureAD\SerhanOZTAS'
password = ''
database = 'DATA_SCIENCE'
servername = r'SerhanOztasAsus\SRNINTLSQLSERVER'
# this is for sql authentication: "mssql+pyodbc://{username}:{password}@{servername}/{database}"
#    "?driver=ODBC+Driver+17+for+SQL+Server"
engine = create_engine(f"mssql+pyodbc://{servername}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes")
print(engine)

In [4]:
database = 'DATA_SCIENCE'
servername = r'SerhanOztasAsus\SRNINTLSQLSERVER'
engine = create_engine(f"mssql+pyodbc://{servername}/{database}"
                       "?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes")
print(engine)

Engine(mssql+pyodbc://SerhanOztasAsus\SRNINTLSQLSERVER/DATA_SCIENCE?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes)

In [5]:
with engine.connect() as conn:
    query = text("SELECT * FROM dbo.sales")
    result = conn.execute(query)
    df = pd.DataFrame(result.fetchall(), columns=result.keys())
df.head().reset_index(drop=True)

,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit,profit_margin_pct,shipping_days,order_year,order_month,order_quarter,SERHAN
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,651.21,524.96,2920025.64,2353920.64,566105.00,19.39,16,2011,1,1,Serhan
1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,47.45,31.79,51008.75,34174.25,16834.50,33.00,26,2015,12,4,Serhan
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,2011-01-13,141515767,2011-02-01,6515,154.06,90.93,1003700.90,592408.95,411291.95,40.98,19,2011,1,1,Serhan
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.27,502.54,5134318.41,3861014.82,1273303.59,24.80,25,2012,9,3,Serhan
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,31.79,165647.95,110978.89,54669.06,33.00,39,2015,10,4,Serhan

In [6]:
with engine.connect() as conn2:
    df_sales = pd.read_sql(text("SELECT * FROM dbo.sales"), conn2)
    df_regiontargets = pd.read_sql(text("SELECT * FROM dbo.region_targets"), conn2)
    df_itemcategories = pd.read_sql(text("SELECT * FROM dbo.item_categories"), conn2)

# df_sales.head().reset_index(drop=True)
#df_regiontargets.head().reset_index(drop=True)
df_itemcategories.head().reset_index(drop=True)

         item_type category  perishable  avg_shelf_days
0  Office Supplies      B2B           0             365
1        Cosmetics      B2C           0             730
2        Household      B2C           0             365
3        Baby Food     Food           1              90
4          Clothes      B2C           0             180

In [5]:
df_sales

,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit,profit_margin_pct,shipping_days,order_year,order_month,order_quarter,SERHAN
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,651.21,524.96,2920025.64,2353920.64,566105.00,19.39,16,2011,1,1,Serhan
1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,47.45,31.79,51008.75,34174.25,16834.50,33.00,26,2015,12,4,Serhan
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,2011-01-13,141515767,2011-02-01,6515,154.06,90.93,1003700.90,592408.95,411291.95,40.98,19,2011,1,1,Serhan
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.27,502.54,5134318.41,3861014.82,1273303.59,24.80,25,2012,9,3,Serhan
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,31.79,165647.95,110978.89,54669.06,33.00,39,2015,10,4,Serhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Asia,Laos,Beverages,Online,H,2014-07-15,199342048,2014-07-31,8597,47.45,31.79,407927.65,273298.63,134629.02,33.00,16,2014,7,3,Serhan
9996,Europe,Liechtenstein,Cosmetics,Online,C,2012-10-27,763044106,2012-11-01,562,437.20,263.33,245706.40,147991.46,97714.94,39.77,5,2012,10,4,Serhan
9997,Sub-Saharan Africa,Democratic Republic of the Congo,Vegetables,Offline,M,2013-02-14,848579967,2013-03-20,2524,154.06,90.93,388847.44,229507.32,159340.12,40.98,34,2013,2,1,Serhan
9998,Sub-Saharan Africa,South Africa,Meat,Online,L,2017-02-19,298185956,2017-02-22,8706,421.89,364.69,3672974.34,3174991.14,497983.20,13.56,3,2017,2,1,Serhan
9999,Asia,Mongolia,Snacks,Offline,M,2016-04-12,824410903,2016-04-16,361,152.58,97.44,55081.38,35175.84,19905.54,36.14,4,2016,4,2,Serhan

select ic.category,
    sum(s.total_revenue) as total_revenue,
    count(*) as order_count,
from sales s
inner join ic on s.item_type=ic.itemptype
group by ic.categroy

In [7]:
df_merge_sales_item = df_sales.merge(df_itemcategories,
                                     how='left',
                                     on='item_type',
                                     suffixes=('_sales', '_itemcat')
                                     )

df_merge_sales_item.head().reset_index(drop=True)

,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,...,total_profit,profit_margin_pct,shipping_days,order_year,order_month,order_quarter,SERHAN,category,perishable,avg_shelf_days
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,651.21,...,566105.00,19.39,16,2011,1,1,Serhan,B2B,0,365
1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,47.45,...,16834.50,33.00,26,2015,12,4,Serhan,Food,1,60
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,2011-01-13,141515767,2011-02-01,6515,154.06,...,411291.95,40.98,19,2011,1,1,Serhan,Food,1,10
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.27,...,1273303.59,24.80,25,2012,9,3,Serhan,B2C,0,365
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,...,54669.06,33.00,39,2015,10,4,Serhan,Food,1,60

# SELECT rt.region,
#        SUM(s.total_revenue) AS actual_revenue,
#        rt.revenue_target,
#        (SUM(s.total_revenue) / rt.revenue_target * 100) AS pct_of_target
# FROM sales s
# INNER JOIN region_targets rt ON s.region = rt.region
# GROUP BY rt.region, rt.revenue_target
# ORDER BY pct_of_target DESC;


    df_sales = pd.read_sql(text("SELECT * FROM dbo.sales"), conn2)
    df_regiontargets = pd.read_sql(text("SELECT * FROM dbo.region_targets"), conn2)
    df_itemcategories = pd.read_sql(text("SELECT * FROM dbo.item_categories"), conn2)

In [8]:
df_sales.head().reset_index(drop=True)

,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit,profit_margin_pct,shipping_days,order_year,order_month,order_quarter,SERHAN
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,651.21,524.96,2920025.64,2353920.64,566105.00,19.39,16,2011,1,1,Serhan
1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,47.45,31.79,51008.75,34174.25,16834.50,33.00,26,2015,12,4,Serhan
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,2011-01-13,141515767,2011-02-01,6515,154.06,90.93,1003700.90,592408.95,411291.95,40.98,19,2011,1,1,Serhan
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.27,502.54,5134318.41,3861014.82,1273303.59,24.80,25,2012,9,3,Serhan
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,31.79,165647.95,110978.89,54669.06,33.00,39,2015,10,4,Serhan

In [9]:
df_regiontargets.head().reset_index(drop=True)

,region,revenue_target,profit_target,priority,SERHAN
0,Europe,55000000,20000000,High,Serhan
1,Asia,65000000,25000000,High,Serhan
2,North America,40000000,15000000,Medium,Serhan
3,Middle East and North Africa,30000000,10000000,Medium,Serhan
4,Sub-Saharan Africa,45000000,17000000,High,Serhan

In [12]:
df_sales_by_region = df_sales.groupby('region').agg({'total_revenue': 'sum'}).rename(columns={'total_revenue': 'actual_revenue'}).reset_index()
df_sales_by_region.head().reset_index(drop=True)

                              region  actual_revenue
0                               Asia    2.005306e+09
1              Australia and Oceania    1.049802e+09
2  Central America and the Caribbean    1.395530e+09
3                             Europe    3.481372e+09
4       Middle East and North Africa    1.715633e+09

#        SUM(s.total_revenue) AS actual_revenue,
#        rt.revenue_target,
#        (SUM(s.total_revenue) / rt.revenue_target * 100) AS pct_of_target

In [14]:
df_merged2 = df_sales_by_region .merge(df_regiontargets,
                                       how='left',
                                       on='region',
                                       suffixes=('_sales_by_region', '_regiontargets')
                                       )
df_merged2.head().reset_index(drop=True)

,region,actual_revenue,revenue_target,profit_target,priority,SERHAN
0,Asia,2.005306e+09,65000000.0,25000000.0,High,Serhan
1,Australia and Oceania,1.049802e+09,NaN,NaN,NaN,NaN
2,Central America and the Caribbean,1.395530e+09,20000000.0,8000000.0,Low,Serhan
3,Europe,3.481372e+09,55000000.0,20000000.0,High,Serhan
4,Middle East and North Africa,1.715633e+09,30000000.0,10000000.0,Medium,Serhan

In [17]:
df_merged2['pct_of_target'] = df_merged2['actual_revenue']/df_merged2['revenue_target']*100
df_merged2.sort_values('pct_of_target',ascending=False)

,region,actual_revenue,revenue_target,profit_target,priority,SERHAN,pct_of_target
6,Sub-Saharan Africa,3.350556e+09,45000000.0,17000000.0,High,Serhan,7445.679501
2,Central America and the Caribbean,1.395530e+09,20000000.0,8000000.0,Low,Serhan,6977.648563
3,Europe,3.481372e+09,55000000.0,20000000.0,High,Serhan,6329.767405
4,Middle East and North Africa,1.715633e+09,30000000.0,10000000.0,Medium,Serhan,5718.778326
0,Asia,2.005306e+09,65000000.0,25000000.0,High,Serhan,3085.085502
5,North America,3.353524e+08,40000000.0,15000000.0,Medium,Serhan,838.381108
1,Australia and Oceania,1.049802e+09,NaN,NaN,NaN,NaN,NaN

# SELECT
#     CASE
#         WHEN total_revenue < 10000  THEN 'Small'
#         WHEN total_revenue < 100000 THEN 'Medium'
#         WHEN total_revenue < 500000 THEN 'Large'
#         ELSE 'XLarge'
#     END AS order_size,
#     AVG(profit_margin_pct) AS avg_margin,
#     COUNT(*) AS order_count
# FROM sales
# GROUP BY order_size
# ORDER BY order_count DESC;

In [26]:
conditions = [
    df_sales['total_revenue'] < 10000 ,
    df_sales['total_revenue'] < 100000,
    df_sales['total_revenue'] < 500000
]
choices = ['small','nedium','large']
default= 'xLarge'

df_sales['order_size'] = np.select(conditions, choices, default=default)
df_sales.head().reset_index()

df_sales_ordersize = df_sales.groupby('order_size').agg(
    avg_margin=('profit_margin_pct','mean'),
    order_count=('order_id','count'),
    total_rev_sum=('total_revenue','sum')
).sort_values('order_count', ascending=False)
    
df_sales_ordersize.reset_index()

  order_size  avg_margin  order_count  total_rev_sum
0     xLarge   33.797260         6273   1.257122e+10
1      large   38.266396         2331   6.945093e+08
2     nedium   31.420708         1257   6.707731e+07
3      small   30.778273          139   7.462796e+05