In [2]:
import pandas as pd
import numpy as np

In [3]:
filepath = r'C:\Users\serha\OneDrive\Desktop\Data_Science_New_Era\Data_Science_New_Era\dataset.csv'
df = pd.read_csv(filepath, parse_dates=['Order Date','Ship Date'])
#df.info()

df[['Region','Order Date','Total Profit']]

                            Region Order Date  Total Profit
0               Sub-Saharan Africa 2011-01-27     566105.00
1                           Europe 2015-12-28      16834.50
2     Middle East and North Africa 2011-01-13     411291.95
3               Sub-Saharan Africa 2012-09-11    1273303.59
4                           Europe 2015-10-27      54669.06
...                            ...        ...           ...
9995                          Asia 2014-07-15     134629.02
9996                        Europe 2012-10-27      97714.94
9997            Sub-Saharan Africa 2013-02-14     159340.12
9998            Sub-Saharan Africa 2017-02-19     497983.20
9999                          Asia 2016-04-12      19905.54

[10000 rows x 3 columns]

In [8]:
df_totprofit = df[df['Total Profit']>500000]
df_totprofit

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,651.21,524.96,2920025.64,2353920.64,566105.00
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.27,502.54,5134318.41,3861014.82,1273303.59
9,Central America and the Caribbean,Haiti,Office Supplies,Online,C,2015-07-04,327881228,2015-07-20,6197,651.21,524.96,4035548.37,3253177.12,782371.25
11,Europe,Bosnia and Herzegovina,Baby Food,Offline,M,2012-10-20,479823005,2012-11-15,9145,255.28,159.42,2334535.60,1457895.90,876639.70
12,Europe,Germany,Office Supplies,Online,C,2015-02-22,498603188,2015-02-27,6618,651.21,524.96,4309707.78,3474185.28,835522.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9981,Asia,Kazakhstan,Clothes,Online,L,2012-03-15,691468608,2012-04-25,9782,109.28,35.84,1068976.96,350586.88,718390.08
9985,Asia,Brunei,Office Supplies,Offline,L,2017-07-19,144625842,2017-07-24,6855,651.21,524.96,4464044.55,3598600.80,865443.75
9986,Europe,Greece,Vegetables,Offline,H,2010-06-06,694237935,2010-06-26,9287,154.06,90.93,1430755.22,844466.91,586288.31
9987,Sub-Saharan Africa,Ghana,Office Supplies,Online,C,2012-10-09,810508048,2012-10-26,6198,651.21,524.96,4036199.58,3253702.08,782497.50
9989,Sub-Saharan Africa,Rwanda,Office Supplies,Online,H,2014-11-27,869780147,2014-12-18,6129,651.21,524.96,3991266.09,3217479.84,773786.25

In [11]:
#Total profit > 50000, Region = Europe

df_mult = df[(df['Total Profit']>50000) & (df['Region']=='Europe')]
df_mult

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,31.79,165647.95,110978.89,54669.06
11,Europe,Bosnia and Herzegovina,Baby Food,Offline,M,2012-10-20,479823005,2012-11-15,9145,255.28,159.42,2334535.60,1457895.90,876639.70
12,Europe,Germany,Office Supplies,Online,C,2015-02-22,498603188,2015-02-27,6618,651.21,524.96,4309707.78,3474185.28,835522.50
19,Europe,Lithuania,Snacks,Offline,H,2011-09-26,878520286,2011-10-02,2530,152.58,97.44,386027.40,246523.20,139504.20
21,Europe,Ukraine,Office Supplies,Online,C,2010-08-14,746630275,2010-08-31,3345,651.21,524.96,2178297.45,1755991.20,422306.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9972,Europe,Lithuania,Beverages,Offline,M,2015-08-02,288644158,2015-09-21,5076,47.45,31.79,240856.20,161366.04,79490.16
9978,Europe,Croatia,Personal Care,Online,M,2012-03-28,144039189,2012-05-14,3252,81.73,56.67,265785.96,184290.84,81495.12
9986,Europe,Greece,Vegetables,Offline,H,2010-06-06,694237935,2010-06-26,9287,154.06,90.93,1430755.22,844466.91,586288.31
9991,Europe,Moldova,Snacks,Offline,H,2010-08-10,579082763,2010-09-02,2313,152.58,97.44,352917.54,225378.72,127538.82
9996,Europe,Liechtenstein,Cosmetics,Online,C,2012-10-27,763044106,2012-11-01,562,437.20,263.33,245706.40,147991.46,97714.94

In [16]:
# WHERE Item Type in Beverages, Snacks, Baby Food

df_mult2 = df[df['Item Type'].isin (['Baby Food','Beverages','Snacks'])]
df_mult2

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,47.45,31.79,51008.75,34174.25,16834.50
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,31.79,165647.95,110978.89,54669.06
5,Sub-Saharan Africa,South Africa,Beverages,Offline,H,2012-07-10,482292354,2012-08-21,9880,47.45,31.79,468806.00,314085.20,154720.80
7,Asia,China,Baby Food,Online,C,2017-04-10,564251220,2017-05-12,3330,255.28,159.42,850082.40,530868.60,319213.80
11,Europe,Bosnia and Herzegovina,Baby Food,Offline,M,2012-10-20,479823005,2012-11-15,9145,255.28,159.42,2334535.60,1457895.90,876639.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,Asia,Laos,Beverages,Offline,C,2015-02-24,651942288,2015-02-28,3066,47.45,31.79,145481.70,97468.14,48013.56
9991,Europe,Moldova,Snacks,Offline,H,2010-08-10,579082763,2010-09-02,2313,152.58,97.44,352917.54,225378.72,127538.82
9993,Australia and Oceania,Marshall Islands,Baby Food,Offline,C,2011-02-22,420056521,2011-04-08,2914,255.28,159.42,743885.92,464549.88,279336.04
9995,Asia,Laos,Beverages,Online,H,2014-07-15,199342048,2014-07-31,8597,47.45,31.79,407927.65,273298.63,134629.02
9999,Asia,Mongolia,Snacks,Offline,M,2016-04-12,824410903,2016-04-16,361,152.58,97.44,55081.38,35175.84,19905.54

In [17]:
# Sales Channel = online, Order Priority in h,c, tot rev>100000

df_mult3 =  df[(df['Sales Channel']=='Online') 
               & (df['Order Priority'].isin (['H','C']))
                & (df['Total Revenue']>100000) ]
df_mult3

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.27,502.54,5134318.41,3861014.82,1273303.59
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,31.79,165647.95,110978.89,54669.06
7,Asia,China,Baby Food,Online,C,2017-04-10,564251220,2017-05-12,3330,255.28,159.42,850082.40,530868.60,319213.80
9,Central America and the Caribbean,Haiti,Office Supplies,Online,C,2015-07-04,327881228,2015-07-20,6197,651.21,524.96,4035548.37,3253177.12,782371.25
12,Europe,Germany,Office Supplies,Online,C,2015-02-22,498603188,2015-02-27,6618,651.21,524.96,4309707.78,3474185.28,835522.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,Sub-Saharan Africa,Ghana,Office Supplies,Online,C,2012-10-09,810508048,2012-10-26,6198,651.21,524.96,4036199.58,3253702.08,782497.50
9989,Sub-Saharan Africa,Rwanda,Office Supplies,Online,H,2014-11-27,869780147,2014-12-18,6129,651.21,524.96,3991266.09,3217479.84,773786.25
9992,Australia and Oceania,East Timor,Household,Online,C,2015-07-12,521562898,2015-08-06,907,668.27,502.54,606120.89,455803.78,150317.11
9995,Asia,Laos,Beverages,Online,H,2014-07-15,199342048,2014-07-31,8597,47.45,31.79,407927.65,273298.63,134629.02
9996,Europe,Liechtenstein,Cosmetics,Online,C,2012-10-27,763044106,2012-11-01,562,437.20,263.33,245706.40,147991.46,97714.94

In [8]:
#Sum Total Revenue, Group by Region

df_sumtotrevregion = df.groupby(['Region']).agg(
    Total_Revenue_region=('Total Revenue','sum')
).reset_index()
#print((df_sumtotrevregion['Total_Revenue_region'].astype(int)))
df_sumtotrevregion['Total_Revenue_region']=df_sumtotrevregion['Total_Revenue_region'].astype(int)
df_sumtotrevregion

                              Region  Total_Revenue_region
0                               Asia            2005305576
1              Australia and Oceania            1049802237
2  Central America and the Caribbean            1395529712
3                             Europe            3481372072
4       Middle East and North Africa            1715633497
5                      North America             335352443
6                 Sub-Saharan Africa            3350555775

In [10]:
# count order id, sum total profit,  avg unit price, group by item type

df_mult_groupby = df.groupby(['Item Type']).agg(
    Count_Order_Id = ('Order ID','count'),
    Sum_Total_Profit = ('Total Profit','sum'),
    AVG_Unit_Price = ('Unit Price','mean')
).reset_index()

df_mult_groupby['Sum_Total_Profit']=df_mult_groupby['Sum_Total_Profit'].astype(int)
df_mult_groupby

          Item Type  Count_Order_Id  Sum_Total_Profit  AVG_Unit_Price
0         Baby Food             842         402324995          255.28
1         Beverages             782          61237427           47.45
2            Cereal             825         372378674          205.70
3           Clothes             872         319636584          109.28
4         Cosmetics             834         713439032          437.20
5            Fruits             795           9774769            9.33
6         Household             875         718738361          668.27
7              Meat             798         227964308          421.89
8   Office Supplies             837         520183203          651.21
9     Personal Care             888         110334844           81.73
10           Snacks             816         227330144          152.58
11       Vegetables             836         267551126          154.06

In [11]:
# Year, Month, Day from Orderdate

df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month
df['Order Day_Name'] = df['Order Date'].dt.day_name()
df['Shipping Days'] = (df['Ship Date']-df['Order Date']).dt.days  # 2024-31-12 - 2024-20-12 = 11

df

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Order Year,Order Month,Order Day_Name,Shipping Days
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,651.21,524.96,2920025.64,2353920.64,566105.00,2011,1,Thursday,16
1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,47.45,31.79,51008.75,34174.25,16834.50,2015,12,Monday,26
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,2011-01-13,141515767,2011-02-01,6515,154.06,90.93,1003700.90,592408.95,411291.95,2011,1,Thursday,19
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.27,502.54,5134318.41,3861014.82,1273303.59,2012,9,Tuesday,25
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,31.79,165647.95,110978.89,54669.06,2015,10,Tuesday,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Asia,Laos,Beverages,Online,H,2014-07-15,199342048,2014-07-31,8597,47.45,31.79,407927.65,273298.63,134629.02,2014,7,Tuesday,16
9996,Europe,Liechtenstein,Cosmetics,Online,C,2012-10-27,763044106,2012-11-01,562,437.20,263.33,245706.40,147991.46,97714.94,2012,10,Saturday,5
9997,Sub-Saharan Africa,Democratic Republic of the Congo,Vegetables,Offline,M,2013-02-14,848579967,2013-03-20,2524,154.06,90.93,388847.44,229507.32,159340.12,2013,2,Thursday,34
9998,Sub-Saharan Africa,South Africa,Meat,Online,L,2017-02-19,298185956,2017-02-22,8706,421.89,364.69,3672974.34,3174991.14,497983.20,2017,2,Sunday,3
9999,Asia,Mongolia,Snacks,Offline,M,2016-04-12,824410903,2016-04-16,361,152.58,97.44,55081.38,35175.84,19905.54,2016,4,Tuesday,4

In [20]:
# sum tot rev group by year, month

df_group_by_date = df.groupby(['Order Year','Order Month']).agg(
    sum_total_revenue = ('Total Revenue','sum')
)

df_group_by_date.sort_values(['Order Year','Order Month'],ascending=False).reset_index()

    Order Year  Order Month  sum_total_revenue
0         2017            7       1.707972e+08
1         2017            6       1.247320e+08
2         2017            5       1.653773e+08
3         2017            4       1.068949e+08
4         2017            3       1.409845e+08
..         ...          ...                ...
86        2010            5       1.250117e+08
87        2010            4       1.201820e+08
88        2010            3       1.356891e+08
89        2010            2       1.317512e+08
90        2010            1       1.569317e+08

[91 rows x 3 columns]