In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine,text

In [2]:
database = 'DATA_SCIENCE'
servername = r'SerhanOztasAsus\SRNINTLSQLSERVER'
engine = create_engine(f"mssql+pyodbc://{servername}/{database}"
                       "?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes")
print(engine)

Engine(mssql+pyodbc://SerhanOztasAsus\SRNINTLSQLSERVER/DATA_SCIENCE?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes)

In [9]:
with engine.connect() as conn:
    df_messy_sales_orders = pd.read_sql(text('SELECT * FROM [DBO].[messy_sales_orders]'),conn)
    df_customer_reference = pd.read_sql(text('SELECT * FROM [dbo].[customer_reference]'),conn)
    df_product_reference  = pd.read_sql(text('SELECT * FROM [dbo].[product_reference]'),conn)
    df_region_targets     = pd.read_sql(text('SELECT * FROM [dbo].[region_targets]'),conn)



df_messy_sales_orders.reset_index()

,index,row_id,order_id,customer_id,customer_email,region,country,product_sku,product_name,sales_channel,...,discount_pct,tax_rate,shipping_cost,payment_method,coupon_code,fulfillment_status,notes,order_id_key,customer_id_key,product_sku_key
0,0,1,ORD-000001,CUST-00002,customer1@example.com,Europe,Germany,SKU-002,Bluetooth Speaker,Offline,...,0.01,0.060,5.74,CARD,,delivered,,ORD-000001,CUST-00002,SKU-002
1,1,2,ORD-000002,CUST-00003,customer2@example.com,Asia Pacific,Japan,SKU-003,Standing Desk,Online,...,0.02,0.070,6.49,PayPal,,delivered,,ORD-000002,CUST-00003,SKU-003
2,2,3,ORD-000003,CUST-00004,customer3@example.com,Latin America,Brazil,SKU-004,Coffee Grinder,Offline,...,0.03,0.080,7.24,wire,,delivered,,ORD-000003,CUST-00004,SKU-004
3,3,4,ORD-000004,CUST-00005,customer4@example.com,Middle East,UAE,SKU-005,Skin Care Kit,Online,...,0.04,0.090,7.99,Cash,,delivered,,ORD-000004,CUST-00005,SKU-005
4,4,5,ORD-000005,CUST-00006,customer5@example.com,Africa,South Africa,SKU-006,Yoga Mat,Offline,...,0.05,0.100,8.74,,NaN,delivered,,ORD-000005,CUST-00006,SKU-006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,11995,11996,ORD-011996,CUST-00497,customer11996@example.com,Asia Pacific,Spain,SKU-005,Skin Care Kit,Online,...,0.26,0.130,24.49,Credit Card,,delivered,,ORD-011996,CUST-00497,SKU-005
11996,11996,11997,ORD-011997,CUST-00498,customer11997@example.com,latam,Kenya,SKU-006,Yoga Mat,Offline,...,0.27,0.050,25.24,Credit Card,,delivered,,ORD-011997,CUST-00498,SKU-006
11997,11997,11998,ORD-011998,CUST-00499,customer11998@example.com,Middle East,Australia,SKU-007,Camping Lamp,Online,...,0.28,0.060,25.99,Credit Card,N/A,delivered,,ORD-011998,CUST-00499,SKU-007
11998,11998,11999,ORD-011999,CUST-00500,customer11999@example.com,Africa,United States,SKU-008,SQL Handbook,Offline,...,0.29,0.070,26.74,credit card,BULK25,delivered,,ORD-011999,CUST-00500,SKU-008
11999,11999,12000,ORD-012000,CUST-00001,customer12000@example.com,North America,Germany,SKU-001,Notebook Pack,Online,...,0.00,0.080,27.49,CARD,NaN,delivered,,ORD-012000,CUST-00001,SKU-001

In [ ]:
# N/A, NA, null, None,"",""Lesson11-Refresh Connection.ipynb"

missing_words = ['', " ", "N/A", "NA", "null", "None", "n/a", "na", "Null", "NULL", "none", "NoneType", "not available"]

df_messy_sales_orders.columns

for column in df_messy_sales_orders.columns:
    #print(df_messy_sales_orders[column].dtype)
    df_messy_sales_orders[column] = df_messy_sales_orders[column].astype('string').str.strip()  # ltrim, rtrim and etc
    df_messy_sales_orders[column] = df_messy_sales_orders[column].replace(missing_words,pd.NA) 


#print(df_messy_sales_orders['coupon_code'] == ' welcome10 ')
df_messy_sales_orders['coupon_code'].str.contains('welcome10', case=False, na=False) 
# select distinct coupon_code,count(*) from messy_sales_orders where coupon_code like '%welcome10%' group by coupon_code

df_messy_sales_orders['coupon_code'].drop_duplicates() # 4 columns, 
df_messy_sales_orders['coupon_code'].dropna().unique()
df_messy_sales_orders['coupon_code'].unique()

df_messy_sales_orders.loc[df_messy_sales_orders['coupon_code'].str.contains('welcome10', case=False, na=False), :].groupby('coupon_code').size().reset_index(name='count')
# select distinct coupon_code,count(*) from messy_sales_orders where coupon_code like '%welcome10%' group by coupon_code
df_messy_sales_orders.loc[df_messy_sales_orders['coupon_code'].isna() | df_messy_sales_orders['coupon_code'].notnull() , :].groupby('coupon_code').size().reset_index(name='count')

# "" -> N/A

Empty DataFrame
Columns: [coupon_code, count]
Index: []

In [25]:
s = '  hello world    '
l = s.split(" ")
print(l)
print(s)
s = s.strip()
print(s)
l = s.split(" ")
print(l)

['', '', 'hello', 'world', '', '', '', '']
  hello world
hello world
['hello', 'world']