In [1]:
import pandas as pd
import numpy as np

In [1]:
pip install SQLAlchemy

Collecting SQLAlchemy
  Downloading sqlalchemy-2.0.49-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from SQLAlchemy)
  Downloading greenlet-3.4.0-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from SQLAlchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading sqlalchemy-2.0.49-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 13.3 MB/s  0:00:00
Downloading greenlet-3.4.0-cp314-cp314-win_amd64.whl (239 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, greenlet, SQLAlchemy

   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   -------------------------- ------------- 2/3 [SQLAlchemy]
   ---------------------------------------- 3/3 [SQLAlchemy]

Successfully installed SQLAlchemy-2.0.49 greenlet-3.4.0 typing-extensions-4.15.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
from sqlalchemy import create_engine,text

In [5]:
pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
username = r'AzureAD\SerhanOZTAS'
password = ''
database = 'DATA_SCIENCE'
servername = r'SerhanOztasAsus\SRNINTLSQLSERVER'
# this is for sql authentication: "mssql+pyodbc://{username}:{password}@{servername}/{database}"
#    "?driver=ODBC+Driver+17+for+SQL+Server"
engine = create_engine(f"mssql+pyodbc://{servername}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes")
print(engine)

Engine(mssql+pyodbc://SerhanOztasAsus\SRNINTLSQLSERVER/DATA_SCIENCE?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes)

In [6]:
with engine.connect() as conn:
    # for table in ['sales', 'item_categories']:
    df = pd.read_sql(text(f'select * from sales'), conn)
    # print(f'table : sales')
    # print(df.to_string())
df.reset_index()

,index,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,...,unit_cost,total_revenue,total_cost,total_profit,profit_margin_pct,shipping_days,order_year,order_month,order_quarter,SERHAN
0,0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,...,524.96,2920025.64,2353920.64,566105.00,19.39,16,2011,1,1,Serhan
1,1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,...,31.79,51008.75,34174.25,16834.50,33.00,26,2015,12,4,Serhan
2,2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,2011-01-13,141515767,2011-02-01,6515,...,90.93,1003700.90,592408.95,411291.95,40.98,19,2011,1,1,Serhan
3,3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,...,502.54,5134318.41,3861014.82,1273303.59,24.80,25,2012,9,3,Serhan
4,4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,...,31.79,165647.95,110978.89,54669.06,33.00,39,2015,10,4,Serhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,Asia,Laos,Beverages,Online,H,2014-07-15,199342048,2014-07-31,8597,...,31.79,407927.65,273298.63,134629.02,33.00,16,2014,7,3,Serhan
9996,9996,Europe,Liechtenstein,Cosmetics,Online,C,2012-10-27,763044106,2012-11-01,562,...,263.33,245706.40,147991.46,97714.94,39.77,5,2012,10,4,Serhan
9997,9997,Sub-Saharan Africa,Democratic Republic of the Congo,Vegetables,Offline,M,2013-02-14,848579967,2013-03-20,2524,...,90.93,388847.44,229507.32,159340.12,40.98,34,2013,2,1,Serhan
9998,9998,Sub-Saharan Africa,South Africa,Meat,Online,L,2017-02-19,298185956,2017-02-22,8706,...,364.69,3672974.34,3174991.14,497983.20,13.56,3,2017,2,1,Serhan
9999,9999,Asia,Mongolia,Snacks,Offline,M,2016-04-12,824410903,2016-04-16,361,...,97.44,55081.38,35175.84,19905.54,36.14,4,2016,4,2,Serhan

In [7]:
with engine.connect( ) as conn:
    df_2 = pd.read_sql(text("""
    SELECT
 TRY_CAST([region] AS NVARCHAR(MAX)) AS [region]
,TRY_CAST([country] AS NVARCHAR(MAX)) AS [country]
,TRY_CAST([item_type] AS NVARCHAR(MAX)) AS [item_type]
,TRY_CAST([sales_channel] AS NVARCHAR(MAX)) AS [sales_channel]

,SUM(TRY_CAST(COALESCE([units_sold],0)		as FLOAT))	AS [units_sold]
,SUM(TRY_CAST(COALESCE([unit_price],0)		as FLOAT))	AS [unit_price]
,SUM(TRY_CAST(COALESCE([unit_cost],0)		as FLOAT))	AS [unit_cost]
,SUM(TRY_CAST(COALESCE([total_revenue],0)	as FLOAT))	AS [total_revenue]
,SUM(TRY_CAST(COALESCE([total_cost],0)		as FLOAT))	AS [total_cost]
,SUM(TRY_CAST(COALESCE([total_profit],0)	as FLOAT))	AS [total_profit]


FROM [dbo].[sales]

GROUP BY
 TRY_CAST([region] AS NVARCHAR(MAX))
,TRY_CAST([country] AS NVARCHAR(MAX)) 
,TRY_CAST([item_type] AS NVARCHAR(MAX)) 
,TRY_CAST([sales_channel] AS NVARCHAR(MAX))
;
"""), conn)
df_2

,region,country,item_type,sales_channel,units_sold,unit_price,unit_cost,total_revenue,total_cost,total_profit
0,Asia,Bangladesh,Baby Food,Online,6432.0,510.56,318.84,1641960.96,1025389.44,616571.52
1,Asia,Bangladesh,Beverages,Offline,3959.0,94.90,63.58,187854.55,125856.61,61997.94
2,Asia,Bangladesh,Cereal,Offline,38394.0,1028.50,585.55,7897645.80,4496321.34,3401324.46
3,Asia,Bangladesh,Cereal,Online,29433.0,822.80,468.44,6054368.10,3446898.63,2607469.47
4,Asia,Bangladesh,Clothes,Offline,5223.0,109.28,35.84,570769.44,187192.32,383577.12
...,...,...,...,...,...,...,...,...,...,...
4002,Sub-Saharan Africa,Zimbabwe,Personal Care,Online,18478.0,163.46,113.34,1510206.94,1047148.26,463058.68
4003,Sub-Saharan Africa,Zimbabwe,Snacks,Offline,2333.0,152.58,97.44,355969.14,227327.52,128641.62
4004,Sub-Saharan Africa,Zimbabwe,Snacks,Online,13981.0,305.16,194.88,2133220.98,1362308.64,770912.34
4005,Sub-Saharan Africa,Zimbabwe,Vegetables,Offline,11441.0,308.12,181.86,1762600.46,1040330.13,722270.33
4006,Sub-Saharan Africa,Zimbabwe,Vegetables,Online,22504.0,462.18,272.79,3466966.24,2046288.72,1420677.52

#   SELECT * FROM sales LIMIT 10000;
#   SELECT * FROM region_targets;
#   SELECT s.*, t.*, 
#          s.total_revenue / s.units_sold AS revenue_per_unit,
#          s.profit_margin_pct - t.target_margin_pct AS margin_gap_vs_target,
#          julianday(s.ship_date) - julianday(s.order_date) AS days_to_ship
#   FROM sales s
#   LEFT JOIN region_targets t ON s.region = t.region
#   WHERE s.units_sold > 0;

In [8]:
with engine.connect( ) as conn:
    df_sales = pd.read_sql (text("SELECT * FROM [dbo].[sales] "),conn)
    df_region = pd.read_sql (text("SELECT * FROM [dbo].[region_targets]"),conn)

In [9]:
df_region['target_margin_pct'] = round(df_region['profit_target']/df_region['revenue_target']*100, 2)
df_region

,region,revenue_target,profit_target,priority,SERHAN,target_margin_pct
0,Europe,55000000,20000000,High,Serhan,36.36
1,Asia,65000000,25000000,High,Serhan,38.46
2,North America,40000000,15000000,Medium,Serhan,37.50
3,Middle East and North Africa,30000000,10000000,Medium,Serhan,33.33
4,Sub-Saharan Africa,45000000,17000000,High,Serhan,37.78
5,Central America and the Caribbean,20000000,8000000,Low,Serhan,40.00
6,Oceania,15000000,5000000,Low,Serhan,33.33

In [10]:
# df_sales.info()

df_merged = df_sales.merge(
    df_region,
    how='left',
    left_on='region',
    right_on='region',
    suffixes=('_sales','_region')
    )

df_merged.head()

,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,...,shipping_days,order_year,order_month,order_quarter,SERHAN_sales,revenue_target,profit_target,priority,SERHAN_region,target_margin_pct
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,651.21,...,16,2011,1,1,Serhan,45000000.0,17000000.0,High,Serhan,37.78
1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,47.45,...,26,2015,12,4,Serhan,55000000.0,20000000.0,High,Serhan,36.36
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,2011-01-13,141515767,2011-02-01,6515,154.06,...,19,2011,1,1,Serhan,30000000.0,10000000.0,Medium,Serhan,33.33
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.27,...,25,2012,9,3,Serhan,45000000.0,17000000.0,High,Serhan,37.78
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,...,39,2015,10,4,Serhan,55000000.0,20000000.0,High,Serhan,36.36

In [11]:
df_merged =df_merged.assign(
    revenue_per_unit=lambda d: d['total_revenue'] / d['units_sold'],
    margin_gap_vs_target=lambda d: d['profit_margin_pct'] - d['target_margin_pct'],
    days_to_ship=lambda d: d['ship_date'] - d['order_date']
)

df_merged.head()

,region,country,item_type,sales_channel,order_priority,order_date,order_id,ship_date,units_sold,unit_price,...,order_quarter,SERHAN_sales,revenue_target,profit_target,priority,SERHAN_region,target_margin_pct,revenue_per_unit,margin_gap_vs_target,days_to_ship
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,2011-01-27,292494523,2011-02-12,4484,651.21,...,1,Serhan,45000000.0,17000000.0,High,Serhan,37.78,651.21,-18.39,16 days
1,Europe,Latvia,Beverages,Online,C,2015-12-28,361825549,2016-01-23,1075,47.45,...,4,Serhan,55000000.0,20000000.0,High,Serhan,36.36,47.45,-3.36,26 days
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,2011-01-13,141515767,2011-02-01,6515,154.06,...,1,Serhan,30000000.0,10000000.0,Medium,Serhan,33.33,154.06,7.65,19 days
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,2012-09-11,500364005,2012-10-06,7683,668.27,...,3,Serhan,45000000.0,17000000.0,High,Serhan,37.78,668.27,-12.98,25 days
4,Europe,Czech Republic,Beverages,Online,C,2015-10-27,127481591,2015-12-05,3491,47.45,...,4,Serhan,55000000.0,20000000.0,High,Serhan,36.36,47.45,-3.36,39 days

df_sales[serhan]
df_region[serhan]

merge on textetxt

df_sales.merge(
    df_region,
    how='left',
    left_on='region_vs',
    right_on='region',
    suffixes=('_sales', '_region')
)